# Generated by Django 2.2.2 on 2019-06-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestbook',
            old_name='rag_date',
            new_name='ragdate',
        ),
    ]
