# Generated by Django 2.2.2 on 2019-06-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_auto_20190620_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestbook',
            old_name='ragdate',
            new_name='regdate',
        ),
    ]
