# Generated by Django 2.2.2 on 2019-06-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
